app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'users' => 'UsersController',
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
	]);

Route::group(['prefix'=>'admin'],function(){
	Route::resource('notas','NotasController');
	Route::resource('nueva', 'NuevaController');
	Route::resource('history', 'HistoryController');
});

app/Notas.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;


class Notas extends Model {

	protected $table = 'notas';
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['id_usuario','fecha', 'importante', 'nota'];

}

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'email', 'password'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

	public function getIDu()
	{
		return $this->id;
		
	}

}

app/Http/Controllers/Controller.php
<?php namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesCommands;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends BaseController {

	use DispatchesCommands, ValidatesRequests;

}

app/Http/Controllers/HistoryController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class HistoryController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('history');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/Http/Controllers/HomeController.php
<?php namespace App\Http\Controllers;

class HomeController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Home Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders your application's "dashboard" for users that
	| are authenticated. Of course, you are free to change or remove the
	| controller as you wish. It is just here to get your app started!
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Show the application dashboard to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('home');
	}

}

app/Http/Controllers/NotasController.php
<?php namespace App\Http\Controllers;
use Illuminate\Routing\Redirector;
use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Request;
use Illuminate\Contracts\Auth\Guard;
use App\Notas;



class NotasController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct(Guard $auth)
	{
		$this->auth = $auth;
		$this->middleware('auth');
	}
	/**
	 * Show the application Notas screen to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		  $user = $this->auth->user()->id;
		  $notast = \DB::table('notas')
		->select(['fecha', 'importante','nota'])
		->where('id_usuario', $user)
		->paginate();
		return view('notas', compact('notast'));
	}
	public function store()
	{
		$nota = new Notas(Request::all());
		$nota->save();
		return redirect()->route('admin.notas.index');
	}
	

}

app/Http/Controllers/NuevaController.php
<?php namespace App\Http\Controllers;

class NuevaController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Show the application dashboard to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('nueva');
	}

}

app/Http/Controllers/UsersController.php
<?php namespace App\Http\Controllers;
use App\User;
class UsersController extends Controller {
	public function getIndex()
	{
		$result = \DB::table('users')
		->select(['name as nombre', 'email'])
		->where('id','>','0')
		->orderBy('id', 'ASC')
		//->join('user_profile', 'user.id', '=', 'user_profiles.user_id')
		->get();
		dd($result);
		return $result;
   }
   public function getOrm()
    {
        $result = User::first();

        dd($result->getIDu());
    }

}

app/Http/Controllers/WelcomeController.php
<?php namespace App\Http\Controllers;

class WelcomeController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Welcome Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders the "marketing page" for the application and
	| is configured to only allow guests. Like most of the other sample
	| controllers, you are free to modify or remove it as you desire.
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('guest');
	}

	/**
	 * Show the application welcome screen to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('welcome');
	}

}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Apuntes</title>

	<link href="{{ asset('/css/app.css') }}" rel="stylesheet">

	<!-- Fonts -->
	<link href='http://127.0.0.1/apuntes/public/css/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Apuntes</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{{ url('/') }}">Inicio</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="{{ url('/auth/login') }}">Login</a></li>
						<li><a href="{{ url('/auth/register') }}">Register</a></li>
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/auth/logout') }}">Cerrar Sesión</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

	@yield('content')

	<!-- Scripts -->
	<script src="//127.0.0.1/apuntes/public/js/jquery.min.js"></script>
	<script src="//127.0.0.1/apuntes/public/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/history.blade.php
@extends('app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			Vista histórico
		</div>
	</div>
	   
</div>
@endsection

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Inicio</div>

				<div class="panel-body">
					Bienvenido, Apuntes es una aplicación gratis puedes usarla cuando quieras durante el tiempo que quieras. :)
					
					<div class="row">
						<br>
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">

								<div class="caption">
									<h3>Nuevo Apunte</h3>
									<p>Añade todos cuantos quieras, no tienen limites. sabemos que manejas muchas cosas al tiempo así que animate a organizarte</p>
									<p><a href="{{route('admin.nueva.index')}}" class="btn btn-primary" role="button">Agregar</a></p>
								</div>
							</div>
						</div>
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								
								<div class="caption">
									<h3>Mis Apuntes</h3>
									<p>Desde aquí obtendrás una vista rápida para la gestión de tus registros actuales, verás que fácil es indicar que terminaste algo.</p>
									<p><a href="{{route('admin.notas.index')}}" class="btn btn-primary" role="button">Verificar</a></p>
								</div>
							</div>
						</div>
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<div class="caption">
									<h3>Históricos</h3>
									<p>Tu información mas remota a tu alcance de tu mano manera rápida, establece un intervalo de fechas o verifica tu rendimiento	.</p>
									<p><a href="{{route('admin.history.index')}}" class="btn btn-primary" role="button">Verificar</a></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/notas.blade.php
@extends('app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<p><b>{{ $notast->total() }}</b> Apuntes</p>
			<a class="btn btn-primary" href="{{ route('admin.nueva.index') }}" role="form-control">Nuevo Apunte</a>
			<table class="table table-striped">
				<tr>
					<th>Fecha</th>
					<th>Imp</th>
					<th>Nota</th>
					<th>Acción</th>
				</tr>
				@foreach ($notast as $nota)
				<tr>
					<td>{{ $nota->fecha }}</td>
					<td>{{ $nota->importante }}</td>
					<td>{{ $nota->nota}}</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-primary btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">Acción <span class="caret"></span>
							</button>
							<ul class="dropdown-menu" role="menu">
								<li><a href="#">Finalizar</a></li>
								<li><a onclick="shoW();">Eliminar</a></li>
							</ul>
						</div>
					</td>
				</tr>
				@endforeach
			</table>
			{!! $notast->render() !!}
		</div>
	</div>
	   <div class="modal fade" id="modalE" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title">Confirmación</h4>
            </div>
            <form role="form" action="" name="frmClientes" onsubmit="Registrar(idP,accion); return false">
              <div class="col-lg-12">
              	<br>
              	<p>¡Un momento! ¿En realidad desea Eliminar este apunte?</p>
                <button type="submit" class="btn btn-primary btn-xs">
                  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Eliminar
                </button>
              </div>
            </form>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger btn-xs" data-dismiss="modal"><i class="fa fa-times"></i>x</button>
            </div>
          </div>
      </div>
  </div>
  <script type="text/javascript">
  function shoW () {
  	$('#modalE').modal('show');
  }
  </script>
</div>
@endsection

resources/views/nueva.blade.php
@extends('app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel-body">
				{!! Form::open(['route' => ['admin.notas.store', 'id_usuario' => Auth::user()->id], 'method'=> 'POST']) !!}
				
				<div class="form-group">
					<label class="col-md-4 control-label">Nivel</label>
					{!! Form::select('importante', ['I' => 'Importante', 'N' => 'Normal', 'P' => 'Poco Importante'], null ,['class' => 'form-control']) !!}
				</div>


				<div class="form-group">
					<label class="col-md-4 control-label">Fecha</label>
					{!! Form::date('fecha', null, ['class' => 'form-control']) !!}
				</div>

				<div class="form-group">
					<label class="col-md-4 control-label">Observación</label>
					{!! Form::textArea('nota', null, ['class' => 'form-control', 'placeholder' => 'Por favor ingrese su apunte', 'Request']) !!}
				</div>

				<div class="form-group">
					<div class="col-md-6 col-md-offset-4">
						<button type="submit" class="btn btn-primary">Crear Apunte</button>
					</div>	
				</div>

				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection